ModulDesignExample/Models/ErrorViewModel.cs
using System;

namespace ModulDesignExample.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ModulDesignExample/Models/Personel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ModulDesignExample.Models
{
    public class Personel
    {
        public string Name { get; set; }

        public string LastName { get; set; }
    }
}

ModulDesignExample/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ModulDesignExample.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ModulDesignExample.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var images = new List<string> { "img1.jpg", "img2.jpg" };
            return View(images);
        }

        public IActionResult Privacy()
        {
            return View();
        }

    }
}

ModulDesignExample/ViewComponets/PersonellerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ModulDesignExample.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ModulDesignExample.ViewComponets
{
    public class PersonellerViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            List<Personel> datas = new List<Personel>
            {
                new Personel{ Name="Nabi",LastName="Nabili"},
                new Personel{ Name="Kamal",LastName="Aliyev"},
                new Personel{ Name="Farhad",LastName="Aliyev"},
            };
            return View(datas);
        }
    }
}

ModulDesignExample/Views/Home/Components/Personeller/Default.cshtml
@model List<Personel>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">LastName</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var personel in Model)
        {
            <tr>
                <td>@personel.Name</td>
                <td>@personel.LastName</td>
            </tr>
        }

    </tbody>
</table>

ModulDesignExample/Views/Home/Partials/_CarouselPartial.cshtml
@model List<string>

@{ 
    var m = Model;
}

<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/images/img1.jpg" height="400" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/images/img2.jpg" height="400" class="d-block w-100" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

ModulDesignExample/Views/Home/Partials/_FooterPartial.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - ModulDesignExample - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

ModulDesignExample/Views/Home/Partials/_HeaderPartial.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Page Header</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

ModulDesignExample/Views/Home/Partials/_LeftMenuPartial.cshtml
<ul class="list-group">
    <li class="list-group-item">Home Page</li>
    <li class="list-group-item">Page 1</li>
    <li class="list-group-item">Page 2</li>
    <li class="list-group-item">Page 3</li>

</ul>

ModulDesignExample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ModulDesignExample</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
  
    <partial name="~/Views/Home/Partials/_HeaderPartial.cshtml"/>

    <div class="container">
        <div class="row">
            <div class="col-md-12">
               <partial name="~/Views/Home/Partials/_CarouselPartial.cshtml" />
            </div>

        </div>

        <div class="row">
            <div class="col-md-2">
                <partial name="~/Views/Home/Partials/_LeftMenuPartial.cshtml" />
            </div>

            <div class="col-md-8">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>

                <div class="row">
                    <div class="col-md-12">
                        @await Component.InvokeAsync("Personeller")
                    </div>

                </div>

            </div>
            <div class="col-md-2"></div>
        </div>

    </div>

    <partial name="~/Views/Home/Partials/_FooterPartial.cshtml" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>